# This compose file is useful for testing https.
# The .env file sets ENVVARS for the Docker CLI used by this compose file.
---
version: "3"
services:
  datastore_weekly:
    build: .
    ports:
      - 8881:8050
    dns:
      - 8.8.8.8
      - 8.8.4.4
    stdin_open: true
    tty: true
    command: ["gunicorn", "--reload", "-b :8050",  "-t 90", "app:server"]
    container_name: datastore_weekly
    hostname: datastore_weekly
    volumes:
      - ./src:/app
    env_file:
      - ./.env

networks:
  default:
    name: a2cps_datastore_net
    external: true
